// MOCK DATA — development only.
// TODO(db): replace every export below with live database queries (Supabase).
// Do not import this file from any server handler that will ship to prod
// without first swapping the source.

import type {
  DocumentRecord,
  Expense,
  MonthlyTask,
  Provider,
  RecurringSubscription,
  SecureRecord,
} from "./types";

export const providers: Provider[] = [
  {
    id: "prov_openai",
    name: "OpenAI",
    category: "AI",
    loginEmail: "benh2477@proton.me",
    billingType: "subscription",
    invoiceSource: "email",
    renewalCycle: "monthly",
    notes: "ChatGPT Plus + API usage on the same account.",
  },
  {
    id: "prov_anthropic",
    name: "Anthropic",
    category: "AI",
    loginEmail: "benh2477@proton.me",
    billingType: "subscription",
    invoiceSource: "email",
    renewalCycle: "monthly",
    notes: "Claude Pro.",
  },
  {
    id: "prov_perplexity",
    name: "Perplexity",
    category: "AI",
    loginEmail: "benh2477@proton.me",
    billingType: "subscription",
    invoiceSource: "portal",
    renewalCycle: "annual",
  },
  {
    id: "prov_webflow",
    name: "Webflow",
    category: "Hosting",
    loginEmail: "benh2477@proton.me",
    billingType: "subscription",
    invoiceSource: "email",
    renewalCycle: "annual",
    notes: "Personal site hosting.",
  },
  {
    id: "prov_stripe",
    name: "Stripe",
    category: "Payments",
    loginEmail: "benh2477@proton.me",
    billingType: "usage",
    invoiceSource: "portal",
    renewalCycle: "monthly",
    notes: "Processing fees on inbound payments.",
  },
  {
    id: "prov_github",
    name: "GitHub",
    category: "Software",
    loginEmail: "benh2477@proton.me",
    billingType: "subscription",
    invoiceSource: "email",
    renewalCycle: "monthly",
  },
];

export const expenses: Expense[] = [
  {
    id: "exp_001",
    providerId: "prov_openai",
    date: "2026-04-03",
    amount: 20,
    currency: "USD",
    audAmount: 31.2,
    category: "AI tools",
    deductible: true,
    invoiceSaved: true,
  },
  {
    id: "exp_002",
    providerId: "prov_anthropic",
    date: "2026-04-05",
    amount: 20,
    currency: "USD",
    audAmount: 31.2,
    category: "AI tools",
    deductible: true,
    invoiceSaved: true,
  },
  {
    id: "exp_003",
    providerId: "prov_perplexity",
    date: "2026-04-11",
    amount: 20,
    currency: "USD",
    audAmount: 31.2,
    category: "AI tools",
    deductible: true,
    invoiceSaved: false,
    notes: "Need to download invoice from portal.",
  },
  {
    id: "exp_004",
    providerId: "prov_github",
    date: "2026-04-14",
    amount: 10,
    currency: "USD",
    audAmount: 15.6,
    category: "Software",
    deductible: true,
    invoiceSaved: true,
  },
  {
    id: "exp_005",
    providerId: "prov_stripe",
    date: "2026-04-18",
    amount: 42.17,
    currency: "AUD",
    audAmount: 42.17,
    category: "Fees",
    deductible: true,
    invoiceSaved: false,
  },
  {
    id: "exp_006",
    providerId: "prov_webflow",
    date: "2026-03-22",
    amount: 276,
    currency: "USD",
    audAmount: 430.56,
    category: "Hosting",
    deductible: true,
    invoiceSaved: true,
    notes: "Annual renewal.",
  },
  {
    id: "exp_007",
    providerId: "prov_openai",
    date: "2026-03-06",
    amount: 20,
    currency: "USD",
    audAmount: 31.2,
    category: "AI tools",
    deductible: true,
    invoiceSaved: true,
  },
];

export const documents: DocumentRecord[] = [
  {
    id: "doc_001",
    title: "OpenAI invoice — April 2026",
    providerId: "prov_openai",
    type: "invoice",
    month: 4,
    taxYear: "FY25-26",
    fileStatus: "saved",
  },
  {
    id: "doc_002",
    title: "Anthropic invoice — April 2026",
    providerId: "prov_anthropic",
    type: "invoice",
    month: 4,
    taxYear: "FY25-26",
    fileStatus: "saved",
  },
  {
    id: "doc_003",
    title: "Perplexity invoice — April 2026",
    providerId: "prov_perplexity",
    type: "invoice",
    month: 4,
    taxYear: "FY25-26",
    fileStatus: "missing",
    notes: "Download from perplexity.ai/settings.",
  },
  {
    id: "doc_004",
    title: "GitHub receipt — April 2026",
    providerId: "prov_github",
    type: "receipt",
    month: 4,
    taxYear: "FY25-26",
    fileStatus: "saved",
  },
  {
    id: "doc_005",
    title: "Stripe fees statement — April 2026",
    providerId: "prov_stripe",
    type: "statement",
    month: 4,
    taxYear: "FY25-26",
    fileStatus: "pending",
  },
  {
    id: "doc_006",
    title: "Webflow invoice — March 2026",
    providerId: "prov_webflow",
    type: "invoice",
    month: 3,
    taxYear: "FY25-26",
    fileStatus: "saved",
  },
];

export const recurring: RecurringSubscription[] = [
  {
    id: "rec_001",
    providerId: "prov_openai",
    amount: 20,
    currency: "USD",
    cadence: "monthly",
    renewalDate: "2026-05-03",
    active: true,
  },
  {
    id: "rec_002",
    providerId: "prov_anthropic",
    amount: 20,
    currency: "USD",
    cadence: "monthly",
    renewalDate: "2026-05-05",
    active: true,
  },
  {
    id: "rec_003",
    providerId: "prov_perplexity",
    amount: 200,
    currency: "USD",
    cadence: "annual",
    renewalDate: "2026-04-29",
    active: true,
  },
  {
    id: "rec_004",
    providerId: "prov_github",
    amount: 10,
    currency: "USD",
    cadence: "monthly",
    renewalDate: "2026-05-14",
    active: true,
  },
  {
    id: "rec_005",
    providerId: "prov_webflow",
    amount: 276,
    currency: "USD",
    cadence: "annual",
    renewalDate: "2027-03-22",
    active: true,
  },
];

export const monthlyTasks: MonthlyTask[] = [
  {
    id: "task_001",
    label: "Download all April invoices",
    month: 4,
    year: 2026,
    status: "in-progress",
    dueDate: "2026-04-30",
  },
  {
    id: "task_002",
    label: "Reconcile business card statement",
    month: 4,
    year: 2026,
    status: "todo",
    dueDate: "2026-05-05",
  },
  {
    id: "task_003",
    label: "Categorise April expenses",
    month: 4,
    year: 2026,
    status: "todo",
    dueDate: "2026-05-07",
  },
  {
    id: "task_004",
    label: "Update AUD conversion rates",
    month: 4,
    year: 2026,
    status: "done",
  },
  {
    id: "task_005",
    label: "File GST quarterly BAS",
    month: 4,
    year: 2026,
    status: "todo",
    dueDate: "2026-04-28",
  },
  {
    id: "task_006",
    label: "Review recurring subscriptions",
    month: 4,
    year: 2026,
    status: "done",
  },
  {
    id: "task_007",
    label: "Archive March documents",
    month: 4,
    year: 2026,
    status: "done",
  },
];

// TODO(encryption): these are placeholder labels only. Never place real TFN,
// bank numbers, or identity values in this file. When wiring Supabase, store
// ciphertext in a secured table and expose only `label` + `maskedValue` to
// the client. Reads must be audit-logged server-side.
export const secureRecords: SecureRecord[] = [
  {
    id: "sec_001",
    label: "Personal TFN",
    maskedValue: "XXX XXX XXX",
    securityLevel: "high",
    notes: "Not yet stored — placeholder only.",
  },
  {
    id: "sec_002",
    label: "ABN",
    maskedValue: "XX XXX XXX XXX",
    securityLevel: "medium",
    notes: "Not yet stored — placeholder only.",
  },
  {
    id: "sec_003",
    label: "Business bank — BSB/Account",
    maskedValue: "XXX-XXX / XXXXXXXX",
    securityLevel: "high",
    notes: "Not yet stored — placeholder only.",
  },
  {
    id: "sec_004",
    label: "myGov recovery email",
    maskedValue: "b•••••@proton.me",
    securityLevel: "medium",
  },
];

export function getProvider(id: string): Provider | undefined {
  return providers.find((p) => p.id === id);
}

export function getProviderName(id: string): string {
  return getProvider(id)?.name ?? "Unknown";
}
